export const SHOPPING_CART_MODAL = 'shopping_cart_modal'
export const BLOCK_CART_MODAL = 'blockcart_modal'
export const LOGIN_MODAL = 'login_modal'
export const REGISTER_MODAL = 'register_modal'
export const FORGOT_MODAL = 'forgot_modal'
